config/routes.rb
EcoEscreening::Application.routes.draw do
  
devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users' => 'devise/registrations#update', :as => 'user_registration'            
    end
  devise_scope :user do
    post "sign_up", :to => "devise/registrations#create"
  end
  get "/qr"=>"drug_tests#qr"
  resources :clinics
  resources :companies
  resources :doctors
  resources :drug_tests
  resources :test_types
  resources :donors do
    collection { post :import }
  end
  resources :selections
  get "/import_data" => "donors#import_data"
  post "/import_data" => "donors#import"

  get "/donor/import" =>"donors#import_data"
  
  get "/users" => "users#index"
  get "/dashboard" =>"welcome#dashboard"
  post "/companies/set_avatar"
  get "/relatorio" =>"drug_tests#relatorio"
  post "/relatorio" =>"drug_tests#result_relatorio"

  get "/states/:id/cities" => "states#cities"

  get "/companies/:id/donors" => "companies#donors"

  get "/companies/:id/users" => "companies#users"

  post "/companies/new" => "companies#create"
  put "/companies/:id/edit" => "companies#update"
  
  get "/user_company"  => "companies#user_company"
  post "/companies/user_set_avatar"
  get "/user_company_index"  => "companies#user_company_index"

  post "/donors/new" => "donors#create"
  put "/donors/:id/edit" => "donors#update"

  post "/doctors/new" => "doctors#create"
  put "/doctors/:id/edit" => "doctors#update"

  post "/clinics/new" => "clinics#create"
  put "/clinics/:id/edit" => "clinics#update"
  get  "users/new" => "users#new"
  post "users/new" => "users#create"
  get  "users/:id/editar" => "users#edit"
  post "users/:id/editar" => "users#update"
  get  "users/:id/change_password" => "users#change_password"
  post "users/:id/change_password" => "users#change_password_save"
  delete "users/:id/destroy" =>"users#delete"
  get "users/:id" => "users#show"
  get "users/:id/index" =>"users#index_user"

  post "/selections/new" => "selections#create"
  put "/selections/:id/edit" => "selections#update"
  get "/selection_by_historical" =>"selections#selection_by_historical"
  get "/selection_random" => "selections#selection_random"
  post "/selection_by_historical" =>"selections#selection_by_historical_new"
  post "/selection_random" => "selections#selection_random_new"
  get "/selection_motivado" => "selections#selection_motivado"
  post "/selection_motivado" => "selections#selection_motivado_new"
  get "selections/success_selection"
  post "/drug_tests/new" => "drug_tests#create"
  put "/drug_tests/:id/edit" => "drug_tests#update"
  get "/testes_pendentes" =>"drug_tests#testes_pendentes"
  get "/testes_realizados" =>"drug_tests#testes_realizados"
  

  post "/test_types/new" => "test_types#create"
  put "/test_types/:id/edit" => "test_types#update"

  authenticated :user do  
    root :to => "welcome#dashboard"
  end

  def after_update_path_for(resource) 
    user_registration_path()
  end 

  root :to => "welcome#index"

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  belongs_to :city
  attr_accessible :address, :id, :name,:city_id, :address_neighbourhood
  validates_presence_of :city_id
end

app/controllers/clinics_controller.rb
# encoding: UTF-8
class ClinicsController < ApplicationController
  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.order("name").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clinics }
    end
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
    @clinic = Clinic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/new
  # GET /clinics/new.json
  def new
    @clinic = Clinic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clinic }
    end
  end

  # GET /clinics/1/edit
  def edit
    @clinic = Clinic.find(params[:id])
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(params[:clinic])
    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clínica foi criada com sucesso.' }
        format.json { render json: @clinic, status: :created, location: @clinic }
      else
        format.html { render action: "new" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clinics/1
  # PUT /clinics/1.json
  def update
    @clinic = Clinic.find(params[:id])
    respond_to do |format|
      if @clinic.update_attributes(params[:clinic])
        format.html { redirect_to @clinic, notice: 'Clínica foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic = Clinic.find(params[:id])
    @clinic.destroy

    respond_to do |format|
      format.html { redirect_to clinics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_edit_form.html.erb
<%= form_for(@clinic) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
        <% @clinic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <fieldset>
      <label>Dados da Clinica</label>

      <section><label for="email_field">Nome</label>
        <div>
          <%= text_field_tag 'clinic[name]',@clinic.name,class: "g5", type: "text"%>
        </div>
      </section>
      <section><label for="">Endereço</label>
        <div>
          <%= text_field_tag 'clinic[address]',@clinic.address, type: "text",class: "g5"%>
          <%= text_field_tag 'clinic[address_neighbourhood]',@clinic.address_neighbourhood, type: "text",class: "g3"%>
          <span style="padding: 0; margin: 0; margin-right: 16px" class="g5">logradouro (rua/avenida, numero, complemento)</span>
          <span style="padding: 0; margin: 0; margin-right: 16px" class="g3">bairro</span>    
          <% if @clinic.city == nil %>
            <%
              state_options = ""
                State.all.each do |state|
                state_options += "<option value=\"#{state.id}\">#{state.name}</option>"
              end 
            %>
            <%= select_tag  'state_id', state_options.html_safe, :prompt => "Estado", id: "cod_estados", style: "width: 97%" ,required: "required"%>    
            <%= select_tag  'clinic[city_id]', "", :prompt => "Cidade", id: "cod_cidades", style: "width: 97%",required: "required" %>
          <% else %>
            <%
              state_options = ""
              state_options_selected = ""

              State.all.each do |state|
                if @clinic.city == nil
                 state_options_selected = ""
                elsif state.id == @clinic.city.state.id
                  state_options_selected = "selected"
                else
                  state_options_selected = ""
                end
                state_options += "<option #{state_options_selected} value=\"#{state.id}\">#{state.name}</option>"
              end 
            %>
            <%
              city_options = ""
              city_options_selected = ""

              cities = City.where(:state_id => @clinic.city.state.id)
              cities.each do |city|
                if @clinic.city == nil
                  city_options_selected = ""
                elsif city.id == @clinic.city.id
                  city_options_selected = "selected"
                else
                 city_options_selected = ""
                end
                city_options += "<option #{city_options_selected} value=\"#{city.id}\">#{city.name}</option>"
              end 
            %>
            
           <%= select_tag  'state_id', state_options.html_safe, prompt: "Estado", id: 'cod_estados', class: 'rounded_form_field',  style: "width: 97%" ,required: "required"%>
           <%= select_tag  'clinic[city_id]', city_options.html_safe, prompt: "Cidade", id: 'cod_cidades', class: 'rounded_form_field',  style: "width: 97%" ,required: "required" %>
          <% end %>
        </div>
      </section>
      <section>
        <div>
          <%= f.submit "Salvar"%>
        </div>
      </section>
    </fieldset>
  </div>
<% end %>

app/views/clinics/_form.html.erb
<%= form_for(@clinic) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
     <fieldset>
        <label>Dados da Clinica</label>

         <section><label for="text_field">Nome</label>
          <div><%= text_field_tag 'clinic[name]',nil,class: "g5", type: "text",required: "required"%></div>
        </section>
        <section><label for="">Endereço</label>
          <div>
            <%= text_field_tag 'clinic[address]',nil, type: "text",class: "g5",required: "required"%>
                <%= text_field_tag 'clinic[address_neighbourhood]',nil, type: "text",class: "g3",required: "required"%>
        <%
          state_options = ""
          State.all.each do |state|
            state_options += "<option value=\"#{state.id}\">#{state.name}</option>"
          end 
        %>
        <%= select_tag  'state_id', state_options.html_safe, :prompt => "Estado", id: "cod_estados", style: "width: 97%",required: "required" %>    
        <%= select_tag  'clinic[city_id]', "", :prompt => "Cidade", id: "cod_cidades", style: "width: 97%" ,required: "required"%>
            
            <span style="padding: 0; margin: 0; margin-right: 16px" class="g5">logradouro (rua/avenida, numero, complemento)</span>
            <span style="padding: 0; margin: 0; margin-right: 16px" class="g3">bairro</span>


          </div>
        </section>
        <section>
        <div>
           <%= f.submit "Cadastrar", :class => "submit"%>
        </div>
      </section>

      </fieldset>
   
  </div>
<% end %>

app/views/clinics/edit.html.erb
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12"> 
		<h1>Editar Clinica</h1>
		<p>Editar informações da clínica.</p>
		<form id="form" action="" method="post" autocomplete="off">
			<%= render 'edit_form' %>
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/clinics/index.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<section id="content" class="content">
  <div class="g12">
    <h1>Clínicas</h1>
    <p>Gerenciar e visualizar as clínicas.</p>
<p>
  <%= link_to 'Nova Clínica', new_clinic_path, class: 'btn' %>
</p>
    <% if @clinics.empty? %>
      <br />
      <h4>Ainda não há clínicas cadastradas, clique em Nova Clínica para cadastrar.</h4>
    <% else %>
      <table class="datatable">
        <thead>
          <tr>
            <th>Nome<div class="icon_order"></th><th>Cidade<div class="icon_order"></th><th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @clinics.each do |clinic| %>
          <tr class="gradeA">

            <td><%= clinic.name %></td>

            <% if  clinic.city == nil
              varcity = '-'
            else
              varcity = clinic.city.name              
             end %>
            <td><%= varcity %></td>
            <td><%= link_to 'Visualizar', clinic, class: 'btn small' %><%= link_to 'Editar', edit_clinic_path(clinic), class: 'btn small' %><%= link_to 'Deletar', clinic, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn small' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</section>

app/views/clinics/new.html.erb
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12"> 
		<h1>Cadastrar Nova Clinica</h1>
		<p>Descrição da seção...</p>
		<form id="form" action="" method="post" autocomplete="off">
			<%= render 'form' %>
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/clinics/show.html.erb
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12">
		<h1>Clínica</h1>
		<p>Informações da clínica.</p>
		<p id="notice"><%= notice %></p>
		<form id="form">
			<fieldset>
				<div><label>Dados da Clínica</label>
				<%= link_to 'Editar', edit_clinic_path(@clinic), class: 'button small' %></div>
				<section><label for="text_field">Nome</label>
					<div>
						<p><%= @clinic.name %></p>
					</div>
				</section>
				<section><label for="">Endereço</label>
					<div>
						<p><%= @clinic.address%><%=" - "%><%= @clinic.address_neighbourhood%></p>
					</div>
				</section>
				<% if  @clinic.city == nil
					varcity = '-'
					varstate = '-'
				   else
				   	varcity = @clinic.city.name
				   	varstate = @clinic.city.state.name
				   end %>
				<section><label for="text_tooltip">Cidade</label>
					<div>
						<p><%= varcity %></p>
					</div>
				</section>
				<section><label for="text_tooltip">Estado</label>
					<div>
						<p><%= varstate %></p>
					</div>
				</section>
			</fieldset>
		</form>
		
		<%= link_to 'Voltar', clinics_path, class: 'button small' %>
	</div>
</section>
<%= render 'welcome/partials/footer' %>