config/routes.rb
EcoEscreening::Application.routes.draw do
  
devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users' => 'devise/registrations#update', :as => 'user_registration'            
    end
  devise_scope :user do
    post "sign_up", :to => "devise/registrations#create"
  end
  get "/qr"=>"drug_tests#qr"
  resources :clinics
  resources :companies
  resources :doctors
  resources :drug_tests
  resources :test_types
  resources :donors do
    collection { post :import }
  end
  resources :selections
  get "/import_data" => "donors#import_data"
  post "/import_data" => "donors#import"

  get "/donor/import" =>"donors#import_data"
  
  get "/users" => "users#index"
  get "/dashboard" =>"welcome#dashboard"
  post "/companies/set_avatar"
  get "/relatorio" =>"drug_tests#relatorio"
  post "/relatorio" =>"drug_tests#result_relatorio"

  get "/states/:id/cities" => "states#cities"

  get "/companies/:id/donors" => "companies#donors"

  get "/companies/:id/users" => "companies#users"

  post "/companies/new" => "companies#create"
  put "/companies/:id/edit" => "companies#update"
  
  get "/user_company"  => "companies#user_company"
  post "/companies/user_set_avatar"
  get "/user_company_index"  => "companies#user_company_index"

  post "/donors/new" => "donors#create"
  put "/donors/:id/edit" => "donors#update"

  post "/doctors/new" => "doctors#create"
  put "/doctors/:id/edit" => "doctors#update"

  post "/clinics/new" => "clinics#create"
  put "/clinics/:id/edit" => "clinics#update"
  get  "users/new" => "users#new"
  post "users/new" => "users#create"
  get  "users/:id/editar" => "users#edit"
  post "users/:id/editar" => "users#update"
  get  "users/:id/change_password" => "users#change_password"
  post "users/:id/change_password" => "users#change_password_save"
  delete "users/:id/destroy" =>"users#delete"
  get "users/:id" => "users#show"
  get "users/:id/index" =>"users#index_user"

  post "/selections/new" => "selections#create"
  put "/selections/:id/edit" => "selections#update"
  get "/selection_by_historical" =>"selections#selection_by_historical"
  get "/selection_random" => "selections#selection_random"
  post "/selection_by_historical" =>"selections#selection_by_historical_new"
  post "/selection_random" => "selections#selection_random_new"
  get "/selection_motivado" => "selections#selection_motivado"
  post "/selection_motivado" => "selections#selection_motivado_new"
  get "selections/success_selection"
  post "/drug_tests/new" => "drug_tests#create"
  put "/drug_tests/:id/edit" => "drug_tests#update"
  get "/testes_pendentes" =>"drug_tests#testes_pendentes"
  get "/testes_realizados" =>"drug_tests#testes_realizados"
  

  post "/test_types/new" => "test_types#create"
  put "/test_types/:id/edit" => "test_types#update"

  authenticated :user do  
    root :to => "welcome#dashboard"
  end

  def after_update_path_for(resource) 
    user_registration_path()
  end 

  root :to => "welcome#index"

end

app/models/donor.rb
#encoding: UTF-8
class Donor < ActiveRecord::Base

  belongs_to :company
  attr_accessible :birth_date, :document_type, :id
  attr_accessible :legal_identifier, :name, :role, :company_id
  attr_accessible :uses_medication, :uses_medication_description, :gender
  has_many :drug_tests
  # attr_accessible :title, :body
  validates_presence_of :company_id
 

  def self.select_random (company, amount)
  	Donor.where('company_id = ?', company.id).order("RANDOM()").limit(amount)
  end

  
  def self.select_random_by_history (company, amount)
    SelectedTest.joins(:drug_test=> :donor).where('selected_tests.result= ?', :positive).group('donors.id').order("RANDOM()").limit(amount)
  end
  def self.to_csv(options = {})
    require 'csv'
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |donor|
        csv << donor.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    return if file == nil
    require 'csv'
    
    CSV.foreach(file.path, headers: true) do |row|
      donor = find_by_id(row["id"]) || new
      donor.attributes = row.to_hash.slice(*accessible_attributes)
      donor.birth_date = DateTime.parse(row["birth_date"])
      donor.save!
    end
  end
end

app/controllers/donors_controller.rb
# encoding: UTF-8
class DonorsController < ApplicationController
  # GET /donors
  # GET /donors.json

  def index
    @donors = Donor.order("name").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  def import_data
    
  end

  def import
   @donor_import = params[:file]
   if @donor_import.present?
      Donor.import(@donor_import)
      redirect_to "/import_data", notice: 'Funcionários importados com sucesso.' 
    else
      redirect_to "/import_data", notice: 'Selecione um arquivo' 
    end
      
  end
  

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
    @donor = Donor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(params[:donor])
    

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Funcionário foi criado com sucesso.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Funcionário foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donors/_edit_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <fieldset>
        <label>Dados do funcionário</label>
         <section><label for="text_field">Empresa</label>  
          <div>  
            <section>
          <div>  
            
            <%  if current_user.admin?%>
               <%if @donor.company == nil %>
                  <%  
                         company_options = ""  
                          Company.all.each do |company|  
                          company_options += "<option value=\"#{company.id}\">#{company.trade_name}</option>"  
                           end   
                        %>  
                      <%= select_tag  'donor[company_id]', company_options.html_safe, :prompt => "Selecione a empresa",required: "required" %>  
               
                <% else %>
                  <%
                      company_options = ""
                      company_options_selected = ""

                      Company.all.each do |company|
                      if company.id == @donor.company.id
                        company_options_selected = "selected"
                      else
                        company_options_selected = ""
                      end
                      company_options += "<option #{company_options_selected} value=\"#{company.id}\">#{company.trade_name}</option>"
                      end 
                    %>
                     <%= select_tag  'donor[company_id]', company_options.html_safe, :prompt => "Selecione a empresa",required: "required" %>  
                <% end %>
            <% else %>
            <%= current_user.company.trade_name%>
            <%= hidden_field_tag "donor[company_id]", current_user.company.id%>
            <% end %>  
          </section> </div> 
            
        </section> 
        
        <section><label for="email_field">Nome</label>
          <div><%= text_field_tag 'donor[name]',@donor.name, type: "text"%></div>
        </section>
        <section><label for="email_field">Sexo</label>
          <div>
            <% 
              if @donor.gender == 'M' 
                selected_gender ='<option value="M" selected="selected">Masculino</option><option value="F">Feminino</option>'
              elsif @donor.gender == 'F' 
                selected_gender ='<option value="M">Masculino</option><option value="F" selected="selected">Feminino</option>'
              else
                selected_gender ='<option value="M">Masculino</option><option value="F">Feminino</option>'
              end
            %>
            <%= select_tag 'donor[gender]', selected_gender.html_safe , :prompt => "Alterar sexo"%>
         </div>
        </section>
        
         <section><label for="text_field">Número do documento</label>
          <div><%= text_field_tag 'donor[legal_identifier]',@donor.legal_identifier, type: "text", class: "g4"%></div>
        </section> 
        <section><label for="text_tooltip">Tipo de documento</label>
        <div>
          <%
              if  @donor.document_type == "CPF"
                selected_document_type ='<option value="CPF" selected="selected">CPF</option><option value="RG">RG</option>'
              elsif @donor.document_type == "RG"
                selected_document_type ='<option value="CPF">CPF</option><option value="RG">RG</option>'
              else
                selected_document_type ='<option value="CPF">CPF</option><option value="RG" selected="selected">RG</option>'
              end
          %>
            <%= select_tag 'donor[document_type]', selected_document_type.html_safe, :prompt => "Selecione" %>
          </div>
       </section>
        <section><label for="3">Data de nascimento</label>
          <div>
            <%= date_select("donor","birth_date", 
              {:start_year => Time.now.year, 
              :end_year =>1920, 
              :order => [:day, :month, :year],
              :prompt => {:day => 'Dia', :month => 'Mês', :year => 'Ano' }}, {:class => "rounded-field"}) %>
            </div>
        </section>
        <section><label for="text_tooltip">Cargo</label>
          <div><%= text_field_tag 'donor[role]',@donor.role, type: "text", class: "g4"%></div>
        </section> 
        <section><label for="text_tooltip">Faz uso de medicação com receita prescrita por um profissional da área médica? </label>
          <div>
             <%if @donor.uses_medication == true %>
                <p>
                <input type="radio" name="donor[uses_medication]" id="choice1" value="false" data-theme="a" onClick="document.getElementById('uses_medication_description').style.display='none';" />
                <label for="choice1">Não</label>
                </p>
                <p>
                <input type="radio" name="donor[uses_medication]" id="choice4" value="true" checked data-theme="a" onClick="document.getElementById('uses_medication_description').style.display='';"/> <label for="choice4">Sim</label>
                </p>
                <div id="uses_medication_description" style="display: "";">         
                <label class="l-auto"></label> 
                 Qual medicamento?
              
                <input type="text" true="true" value="<%=@donor.uses_medication_description%>" size = 30 name="donor[uses_medication_description]">
              <% else %>
                <p>
                <input type="radio" name="donor[uses_medication]" id="choice1" value="false" checked data-theme="a" onClick="document.getElementById('uses_medication_description').style.display='none';" />
                <label for="choice1">Não</label>
                </p>
                    <p>
                <input type="radio" name="donor[uses_medication]" id="choice4" value="true" data-theme="a" onClick="document.getElementById('uses_medication_description').style.display='';"/> <label for="choice4">Sim</label>
                </p>
                <div id="uses_medication_description" style="display: none;">         
                <label class="l-auto"></label> 
                 Qual medicamento?
                <input type="text" true="true" size = 30 name="donor[uses_medication_description]">
              <% end %>
          </div>
          </div>
        </section>
        <section>
        <div>
           <%= f.submit "Salvar"%>
        </div>
      </section>
      </fieldset> 
    
  </div>
<% end %>

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <fieldset>
        <label>Dados do funcionário</label>
         <section><label for="text_field">Empresa</label>  
          <div>  
            
            <%  if current_user.admin? %>
            <%  
                   company_options = ""  
                    Company.all.each do |company|  
                    company_options += "<option value=\"#{company.id}\">#{company.trade_name}</option>"  
                     end   
                  %>  
                <%= select_tag  'donor[company_id]', company_options.html_safe, :prompt => "Selecione a empresa",required: "required" %>
                <% else %>
            <%= current_user.company.trade_name%>
            <%= hidden_field_tag "donor[company_id]", current_user.company.id%>
            <% end %>  
          </section> 
          
        <section><label for="email_field">Nome</label>
          <div><%= text_field_tag 'donor[name]',nil, type: "text",required: "required"%></div>
        </section>
        <section><label for="email_field">Sexo</label>
          <div><%= select_tag 'donor[gender]', '<option value="M">Masculino</option><option value="F">Feminino</option>'.html_safe, :prompt => "Sexo" %>
          </div>
        </section>
         <section><label for="text_field">Número do documento</label>
          <div><%= text_field_tag 'donor[legal_identifier]',nil, type: "text", class: "g4",required: "required"%></div>
        </section> 
        <section><label for="text_tooltip">Tipo de documento</label>
        <div>
          <%= select_tag 'donor[document_type]', '<option value="CPF">CPF</option><option value="RG" selected="selected">RG</option>'.html_safe, :prompt => "Selecione" %>
          </div>
       </section>
        <section><label for="3">Data de nascimento</label>
          <div>
            <%= date_select("donor","birth_date", 
              {:start_year => Time.now.year, 
              :end_year =>1920, 
              :order => [:day, :month, :year],
              :prompt => {:day => 'Dia', :month => 'Mês', :year => 'Ano' }}, {:class => "rounded-field"}) %>
            </div>
        </section>
        <section><label for="text_tooltip">Cargo</label>
          <div><%= text_field_tag 'donor[role]',nil, type: "text", class: "g4",required: "required"%></div>
        </section>
        <section><label for="text_tooltip">Faz uso de medicação com receita prescrita por um profissional da área médica? </label>
          <div>
            <p>
              <input type="radio" name="donor[uses_medication]" id="choice1" value="false" data-theme="a" onClick="document.getElementById('uses_medication_description').style.display='none';" />
              <label for="choice1">Não</label>
            </p>
            <p>
              <input type="radio" name="donor[uses_medication]" id="choice4" value="true" data-theme="a" onClick="document.getElementById('uses_medication_description').style.display='';"/> <label for="choice4">Sim</label>
            </p>
            <div id="uses_medication_description" style="display: none;">         
              <label class="l-auto"></label> 
              Qual medicamento? 
              <input type="text" true="true"  size = 30 name="donor[uses_medication_description]">
            </div>
          </div>
        </section>
       
        <section>
          <div>
             <%= f.submit "Cadastrar" %>
          </div>
        </section>
      </fieldset> 
    
  </div>
<% end %>

app/views/donors/edit.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<section class="content">
	<div class="g12">
		<h1>Editar Funcionário</h1>
		<p>Editar dados do funcionário</p>
		<form id="form" action="" method="post" autocomplete="off">
				<%= render 'edit_form' %>	
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/donors/import_data.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<section  class="content">
  <div class="g12">
  <h1>Importar funcionários de um arquivo CSV</h1>
		<p>Importe funcionários por meio de um planilha no formato CSV (comma-separated values)</p>

  <h3>Importar Funcionários</h3>

  <%= form_tag import_donors_path, multipart: true do %>

  
  <p  class="notice"><h4 style="color:red"><%= notice %></h4></p>
    <%= file_field_tag :file, :accept => "csv" %>
    <%= submit_tag "Importar", class: "submit" %>
  <% end %>
    <p><b>IMPORTANTE:</b> Esta é uma operação avançada que deve ser acompanhada por um técnico especializado ou pelo administrador do sistema.</p>
    <p><b>PRÉ-REQUISITOS:</b> O arquivo CSV (comma-separated values) enviado deve possuir:</p>
    <ul>
      <li>Extensão ".csv";</li>
      <li>Codificação UTF-8;</li>
      <li>Nome do arquivo composto apenas por caractéres alfanuméricos (a-z, A-Z, 0-9) e caractéres: "_", "-" e "."</li>
    </ul>
  </div>
</section>

app/views/donors/index.html.erb
<%= stylesheet_link_tag 'print', :media => 'print' %>
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<script type="text/javascript">
  function DoPrinting() {
       if (!window.print){
               alert("Use o Netscape  ou Internet Explorer \n nas versões 4.0 ou superior!")
               return
       }
       window.print()
  }
</script>
<section id="content" class="content  noprint-relatorio-content">
  <div class="g12">
   <h1  class="noprint-noshadow">Funcionários</h1>
    <p class="noprint-noshadow">Gerenciar e visualizar os funcionários<br/><a href="#" onclick="DoPrinting()" class="noprint">Imprimir</a> </p>
  <p class="noprint"> 
  <%= link_to 'Novo Funcionário', new_donor_path, class: 'btn' %>
  </p>

   <%  if not current_user.admin? %>
          <% @donors = Donor.where("company_id = ?", current_user.company_id) %>
        <% end %>
    <% if @donors.empty? %>
    <br />
    <h4>Ainda não há funcionários cadastrados, clique em Novo Funcionário para cadastrar.</h4>
    <% else %>
  
    <table class="datatable">
      <thead>
        <tr>
          <th class="noprint-noshadow">Nome<div class="icon_order"></th>
          <th class="noprint-noshadow">Número do documento<div class="icon_order"></th>
          <th class="noprint-noshadow">Data de nascimento<div class="icon_order"></th>
          <th class="noprint-noshadow">Cargo<div class="icon_order"></th>
          <th class="noprint">Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @donors.each do |donor| %>
        <tr class="gradeA">
          <td class="noprint-noshadow"><%= donor.name %></td>
          <td class="noprint-noshadow"><%= donor.legal_identifier  %></td>
          <% if donor.birth_date == nil %>
            <td class="noprint-noshadow"><%=  %>
              <% else %>
          <td class="noprint-noshadow"><%= donor.birth_date.strftime("%d/%m/%Y") %></td><% end %><td class="noprint-noshadow"><%= donor.role%></td></td><td class="noprint"><%= link_to 'Visualizar', donor, class: 'btn small' %><%= link_to 'Editar', edit_donor_path(donor), class: 'btn small' %><%= link_to 'Deletar', donor, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn small' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>

</section>

  <br />
<%= render 'welcome/partials/footer' %>

app/views/donors/new.html.erb
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<section class="content">
	<div class="g12">
		<h1>Cadastrar Novo Funcionário</h1>
		<p>Insira os dados do funcionário e cadastre</p>
		<form id="form" action="" method="post" autocomplete="off">
				<%= render 'form' %>	
		</form>
		
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/donors/show.html.erb
<%= stylesheet_link_tag 'print', :media => 'print' %>

<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<script type="text/javascript">
  function DoPrinting() {
       if (!window.print){
               alert("Use o Netscape  ou Internet Explorer \n nas versões 4.0 ou superior!")
               return
       }
       window.print()
  }
</script>
<section class="content noprint-relatorio-content">
	<div class="g12">
		<h1 class="noprint-noshadow">Funcionário</h1>
    <p class="noprint-noshadow">Informações do funcionário<br/><a href="#" onclick="DoPrinting()" class="noprint">Imprimir</a> </p>
		
		<p id="notice"><%= notice %></p>
		<form id="form">
			<fieldset>
		
				<div ><label class="noprint-noshadow">Dados do funcionário</label><%= link_to 'Editar', edit_donor_path(@donor), class: 'button small noprint' %></div>
				<section><label class="noprint-noshadow" for="text_field">ID da Empresa</label>
					<div>
						<p class="noprint-noshadow"><%= @donor.company_id %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="">Nome</label>
					<div>
						<p class="noprint-noshadow"><%= @donor.name %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="">Sexo</label>
					<div>
						<% if @donor.gender == 'M' %>
			                <p class="noprint-noshadow"><%= "Masculino" %></p>
			             <% elsif @donor.gender == 'F'%>
			             	<p class="noprint-noshadow"><%= "Feminino" %></p>
			             <% end %>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="">Número do documento</label>
					<div>
						<p class="noprint-noshadow"><%= @donor.legal_identifier %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Tipo do documento</label>
					<div>
						<p class="noprint-noshadow"><%= @donor.document_type %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Data de nascimento</label>
					<div>
						<p class="noprint-noshadow"><%= @donor.birth_date.strftime("%d/%m/%Y") %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Cargo</label>
					<div>
						<p class="noprint-noshadow"><%= @donor.role %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Faz uso de medicação com receita prescrita por um profissional da área da médica?</label>
					<div>
						<%if @donor.uses_medication == true %>
               				<p class="noprint-noshadow">Sim, <%= @donor.uses_medication_description %></p>
		              	<% else %>
		                	<p class="noprint-noshadow"><%= "Não faz uso de medicação."%></p>
		             	<% end %>
					</div>
				</section>
			</fieldset>
		</form>
		<%= link_to 'Voltar', donors_path, class: 'button small noprint' %>
	</div>
</section>
<%= render 'welcome/partials/footer' %>