config/routes.rb
EcoEscreening::Application.routes.draw do
  
devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users' => 'devise/registrations#update', :as => 'user_registration'            
    end
  devise_scope :user do
    post "sign_up", :to => "devise/registrations#create"
  end
  get "/qr"=>"drug_tests#qr"
  resources :clinics
  resources :companies
  resources :doctors
  resources :drug_tests
  resources :test_types
  resources :donors do
    collection { post :import }
  end
  resources :selections
  get "/import_data" => "donors#import_data"
  post "/import_data" => "donors#import"

  get "/donor/import" =>"donors#import_data"
  
  get "/users" => "users#index"
  get "/dashboard" =>"welcome#dashboard"
  post "/companies/set_avatar"
  get "/relatorio" =>"drug_tests#relatorio"
  post "/relatorio" =>"drug_tests#result_relatorio"

  get "/states/:id/cities" => "states#cities"

  get "/companies/:id/donors" => "companies#donors"

  get "/companies/:id/users" => "companies#users"

  post "/companies/new" => "companies#create"
  put "/companies/:id/edit" => "companies#update"
  
  get "/user_company"  => "companies#user_company"
  post "/companies/user_set_avatar"
  get "/user_company_index"  => "companies#user_company_index"

  post "/donors/new" => "donors#create"
  put "/donors/:id/edit" => "donors#update"

  post "/doctors/new" => "doctors#create"
  put "/doctors/:id/edit" => "doctors#update"

  post "/clinics/new" => "clinics#create"
  put "/clinics/:id/edit" => "clinics#update"
  get  "users/new" => "users#new"
  post "users/new" => "users#create"
  get  "users/:id/editar" => "users#edit"
  post "users/:id/editar" => "users#update"
  get  "users/:id/change_password" => "users#change_password"
  post "users/:id/change_password" => "users#change_password_save"
  delete "users/:id/destroy" =>"users#delete"
  get "users/:id" => "users#show"
  get "users/:id/index" =>"users#index_user"

  post "/selections/new" => "selections#create"
  put "/selections/:id/edit" => "selections#update"
  get "/selection_by_historical" =>"selections#selection_by_historical"
  get "/selection_random" => "selections#selection_random"
  post "/selection_by_historical" =>"selections#selection_by_historical_new"
  post "/selection_random" => "selections#selection_random_new"
  get "/selection_motivado" => "selections#selection_motivado"
  post "/selection_motivado" => "selections#selection_motivado_new"
  get "selections/success_selection"
  post "/drug_tests/new" => "drug_tests#create"
  put "/drug_tests/:id/edit" => "drug_tests#update"
  get "/testes_pendentes" =>"drug_tests#testes_pendentes"
  get "/testes_realizados" =>"drug_tests#testes_realizados"
  

  post "/test_types/new" => "test_types#create"
  put "/test_types/:id/edit" => "test_types#update"

  authenticated :user do  
    root :to => "welcome#dashboard"
  end

  def after_update_path_for(resource) 
    user_registration_path()
  end 

  root :to => "welcome#index"

end

app/controllers/test_types_controller.rb
class TestTypesController < ApplicationController
  # GET /test_types
  # GET /test_types.json
  before_filter :checked_user
  def index
    @test_types = TestType.order("name").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @test_types }
    end
  end

  # GET /test_types/1
  # GET /test_types/1.json
  def show
    @test_type = TestType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @test_type }
    end
  end

  # GET /test_types/new
  # GET /test_types/new.json
  def new
    @test_type = TestType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @test_type }
    end
  end

  # GET /test_types/1/edit
  def edit
    @test_type = TestType.find(params[:id])
  end

  # POST /test_types
  # POST /test_types.json
  def create
    @test_type = TestType.new(params[:test_type])

    respond_to do |format|
      if @test_type.save
        format.html { redirect_to @test_type, notice: 'Tipo de Teste foi criado com sucesso.' }
        format.json { render json: @test_type, status: :created, location: @test_type }
      else
        format.html { render action: "new" }
        format.json { render json: @test_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /test_types/1
  # PUT /test_types/1.json
  def update
    @test_type = TestType.find(params[:id])

    respond_to do |format|
      if @test_type.update_attributes(params[:test_type])
        format.html { redirect_to @test_type, notice: 'Tipo de Teste foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @test_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_types/1
  # DELETE /test_types/1.json
  def destroy
    @test_type = TestType.find(params[:id])
    @test_type.destroy

    respond_to do |format|
      format.html { redirect_to test_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/test_types_helper.rb
module TestTypesHelper
end

app/views/test_types/_edit_form.html.erb
<%= form_for(@test_type) do |f| %>
  <% if @test_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_type.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
      <% @test_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <fieldset>
        <label>Dados do tipo de droga</label>
        <section><label for="text_field">Nome</label>
          <div><%= text_field_tag 'test_type[name]', @test_type.name, type: "text",class: "g4"%></div>
        </section>
        <section><label for="text_field">Abreviação</label>
          <div><%= text_field_tag 'test_type[short_name]', @test_type.short_name, type: "text", class: "g4",required: "required"%></div>
        </section>
         <section><label for="text_field">Material coletado</label>
          <div><%= select_tag 'test_type[collected_material]', '<option>Ar Alveolar</option><option>Saliva</option><option>Sangue</option><option>Urina</option>'.html_safe, :prompt => @test_type.collected_material %></div>
        </section>
        <section><label for="text_field">Descrição</label>
          <div><%= text_field_tag 'test_type[description]', @test_type.description, type: "text"%></div>
        </section>
        <section>
        <div>
           <%= f.submit "Salvar", :class => "submit"%>
        </div>
      </section>
    </fidelset>
  </div>
<% end %>

app/views/test_types/_form.html.erb
<%= form_for(@test_type) do |f| %>
  <% if @test_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_type.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
      <% @test_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <fieldset>
        <label>Dados do tipo de droga</label>
        <section><label for="text_field">Nome</label>
          <div><%= text_field_tag 'test_type[name]', nil, type: "text", class: "g4",required: "required"%></div>
        </section>
        <section><label for="text_field">Abreviação</label>
          <div><%= text_field_tag 'test_type[short_name]', nil, type: "text", class: "g4",required: "required"%></div>
        </section>
        <section><label for="text_field">Material coletado</label>
          <div><%= select_tag 'test_type[collected_material]', '<option>Ar Alveolar</option><option>Saliva</option><option>Sangue</option><option>Urina</option>'.html_safe, :prompt => "Selecione" %></div>
        </section>
        <section><label for="text_field">Descrição</label>
          <div><%= text_field_tag 'test_type[description]', nil, type: "text"%></div>
        </section>
       <section>
        <div>
           <%= f.submit "Cadastrar", :class => "submit"%>
        </div>
      </section>
    </fidelset>
  </div>
<% end %>

app/views/test_types/edit.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12"> 
		<h1>Editar Tipo de Droga</h1>
		<p>Editar o tipo de droga.</p>
		<form id="form" action="" method="post" autocomplete="off">
			<%= render 'edit_form' %>
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/test_types/index.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<section id="content" class="content">
  <div class="g12">
    <h1>Tipos de Drogas</h1>
    <p>Gerenciar e visualizar os tipos de drogas.</p>
  <p><%= link_to 'Novo Tipo de Droga', new_test_type_path, class: 'btn' %></p>

    <% if @test_types.empty? %>
    <br />
    <h4>Ainda não possui nenhum tipo de droga cadastrado, clique em Novo Tipo de Droga e cadastre.</h4>
    <% else %>
    <table class="datatable">
      <thead>
        <tr>
          <th>Name<div class="icon_order"></th><th>Abreviação<div class="icon_order"></th><th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @test_types.each do |test_type| %>
        <tr class="gradeA">
          <td><%= test_type.name %></td><td><%= test_type.short_name %></td><td><%= link_to 'Visualizar', test_type, class: 'btn small' %><%= link_to 'Editar', edit_test_type_path(test_type), class: 'btn small' %><%= link_to 'Deletar', test_type, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn small' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</section>
<%= render 'welcome/partials/footer' %>

app/views/test_types/new.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12"> 
		<h1>Cadastrar Novo Tipo de Droga</h1>
		<p>Preencha as informações do novo tipo de droga.</p>
		<form id="form" action="" method="post" autocomplete="off">
			<%= render 'form' %>
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/test_types/show.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12">
		<h1>Tipo de Droga</h1>
		<p>Informações do tipo de droga.</p>
		<p id="notice"><%= notice %></p>
		<form id="form">
			<fieldset>
				<div><label>Dados do tipo de droga</label>   
		<%= link_to 'Editar', edit_test_type_path(@test_type), class: 'button small' %>
	</div>
				<section><label for="text_field">Nome</label>
					<div>
						<p><%= @test_type.name %></p>
					</div>
				</section>
				<section><label for="text_field">Abreviação</label>
					<div>
						<p><%= @test_type.short_name %></p>
					</div>
				</section>
				<section><label for="">Material coletado</label>
					<div>
						<p><%= @test_type.collected_material %></p>
					</div>
				</section>
				<section><label for="">Descrição</label>
					<div>
						<p><%= @test_type.description %></p>
					</div>
				</section>
			</fieldset>
		</form>
		<%= link_to 'Voltar', test_types_path, class: 'button small' %>
	</div>
</section>
<%= render 'welcome/partials/footer' %>