config/routes.rb
EcoEscreening::Application.routes.draw do
  
devise_for :users, :skip => [:registrations]                                          
    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
      put 'users' => 'devise/registrations#update', :as => 'user_registration'            
    end
  devise_scope :user do
    post "sign_up", :to => "devise/registrations#create"
  end
  get "/qr"=>"drug_tests#qr"
  resources :clinics
  resources :companies
  resources :doctors
  resources :drug_tests
  resources :test_types
  resources :donors do
    collection { post :import }
  end
  resources :selections
  get "/import_data" => "donors#import_data"
  post "/import_data" => "donors#import"

  get "/donor/import" =>"donors#import_data"
  
  get "/users" => "users#index"
  get "/dashboard" =>"welcome#dashboard"
  post "/companies/set_avatar"
  get "/relatorio" =>"drug_tests#relatorio"
  post "/relatorio" =>"drug_tests#result_relatorio"

  get "/states/:id/cities" => "states#cities"

  get "/companies/:id/donors" => "companies#donors"

  get "/companies/:id/users" => "companies#users"

  post "/companies/new" => "companies#create"
  put "/companies/:id/edit" => "companies#update"
  
  get "/user_company"  => "companies#user_company"
  post "/companies/user_set_avatar"
  get "/user_company_index"  => "companies#user_company_index"

  post "/donors/new" => "donors#create"
  put "/donors/:id/edit" => "donors#update"

  post "/doctors/new" => "doctors#create"
  put "/doctors/:id/edit" => "doctors#update"

  post "/clinics/new" => "clinics#create"
  put "/clinics/:id/edit" => "clinics#update"
  get  "users/new" => "users#new"
  post "users/new" => "users#create"
  get  "users/:id/editar" => "users#edit"
  post "users/:id/editar" => "users#update"
  get  "users/:id/change_password" => "users#change_password"
  post "users/:id/change_password" => "users#change_password_save"
  delete "users/:id/destroy" =>"users#delete"
  get "users/:id" => "users#show"
  get "users/:id/index" =>"users#index_user"

  post "/selections/new" => "selections#create"
  put "/selections/:id/edit" => "selections#update"
  get "/selection_by_historical" =>"selections#selection_by_historical"
  get "/selection_random" => "selections#selection_random"
  post "/selection_by_historical" =>"selections#selection_by_historical_new"
  post "/selection_random" => "selections#selection_random_new"
  get "/selection_motivado" => "selections#selection_motivado"
  post "/selection_motivado" => "selections#selection_motivado_new"
  get "selections/success_selection"
  post "/drug_tests/new" => "drug_tests#create"
  put "/drug_tests/:id/edit" => "drug_tests#update"
  get "/testes_pendentes" =>"drug_tests#testes_pendentes"
  get "/testes_realizados" =>"drug_tests#testes_realizados"
  

  post "/test_types/new" => "test_types#create"
  put "/test_types/:id/edit" => "test_types#update"

  authenticated :user do  
    root :to => "welcome#dashboard"
  end

  def after_update_path_for(resource) 
    user_registration_path()
  end 

  root :to => "welcome#index"

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :city
  attr_accessible :address, :contact_email, :contact_name, :contact_phone, :id
  attr_accessible  :legal_identifier, :legal_name, :trade_name, :city_id,:address_neighbourhood
  validates_presence_of  :city_id
end

app/controllers/companies_controller.rb
#encoding: utf-8
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order("legal_name").all

    respond_to do |format|
      if current_user.admin?
        format.html # index.html.erb
        format.json { render json: @companies }
      else
        format.html {render "public/403.html"}
      end
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    respond_to do |format|
      if current_user.admin?
          format.html # index.html.erb
          format.json { render json: @companies }
      else
          format.html {render "public/403.html"}
      end
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    respond_to do |format|
    if current_user.admin?
        format.html # index.html.erb
        format.json { render json: @companies }
    else
        format.html {render "public/403.html"}
      end
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
    if not current_user.admin?
      render "public/403.html"
    end
  end

  # POST /companies
  # POST /companies.json
  def create
    
    @company = Company.new(params[:company])
    
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Empresa foi criada com sucesso.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Empresa foi atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  
  
  def donors
    @company = Company.find_by_id (params[:id])
    @donors = Donor.order("name").where("company_id = ?", @company.id)

    options = ""
    @donors.each do |donor|
      options += "<option value=\"#{donor.id}\" > #{donor.name}</option>"
    end
    render text: options
  end
  
  def users
    @company = Company.find_by_id (params[:id])
    @users = User.order("name").where("company_id = ?", @company.id)

    options = ""
    @users.each do |user|
      options += "<option value=\"#{user.name}\" > #{user.name}</option>"
    end
    render text: options
  end


  def user_company_index
    @company = Company.find_by_id(current_user.company_id)
  end

  def user_company
    @company = Company.find_by_id(current_user.company_id)
  end

  def set_avatar
    @current_user  = Company.find(params[:id])
    @avatar_errors = Array.new

    respond_to do |format|
      format.html { 
        if not params[:avatar].blank?
          @avatar = params[:avatar].first
          if FastImage.size(@avatar.tempfile) == [198, 71] then
            if @avatar.content_type == "image/jpeg" || @avatar.content_type == "image/png"

              if @avatar.content_type == "image/jpeg"
                @format = "jpg"
                if File.exist?("./public/uploads/images/companies/#{@current_user.id}.png")
                  FileUtils.rm("./public/uploads/images/companies/#{@current_user.id}.png")
                end
              elsif @avatar.content_type == "image/png"
                @format = "png"
                if File.exist?("./public/uploads/images/companies/#{@current_user.id}.jpg")
                  FileUtils.rm("./public/uploads/images/companies/#{@current_user.id}.jpg")
                end
              end

              @avatar_file = "./public/uploads/images/companies/#{@current_user.id}.#{@format}"
                
              FileUtils.cp(@avatar.tempfile, @avatar_file)
              if File.exist?(@avatar.tempfile)
                redirect_to @current_user
              else
                @avatar_errors.push("Não foi possível fazer o upload da sua imagem. Tente novamente mais tarde.")
               redirect_to @current_user, notice: @avatar_errors
              end
            else
              @avatar_errors.push("O formato da imagem é inválido. A imagem deve estar no formato JPEG ('*.jpg') ou PNG ('*.png').")
              redirect_to @current_user, notice: @avatar_errors
            end
          else
            @avatar_errors.push("O tamanho da imagem deve ser de exatamente 198 por 71 pixels (198x71px).")
            redirect_to @current_user, notice: @avatar_errors
          end
        else
          @avatar_errors.push("Selecione uma imagem do seu computador.")
          redirect_to @current_user, notice: @avatar_errors
        end
      }
    end
  end

  def user_set_avatar
    @current_user = current_user

    @avatar_errors = Array.new

    respond_to do |format|
      format.html { 
        if not params[:avatar].blank?
          @avatar = params[:avatar].first
          if FastImage.size(@avatar.tempfile) == [198, 71] then
            if @avatar.content_type == "image/jpeg" || @avatar.content_type == "image/png"

              if @avatar.content_type == "image/jpeg"
                @format = "jpg"
                if File.exist?("./public/uploads/images/companies/#{@current_user.company.id}.png")
                  FileUtils.rm("./public/uploads/images/companies/#{@current_user.company.id}.png")
                end
              elsif @avatar.content_type == "image/png"
                @format = "png"
                if File.exist?("./public/uploads/images/companies/#{@current_user.company.id}.jpg")
                  FileUtils.rm("./public/uploads/images/companies/#{@current_user.company.id}.jpg")
                end
              end

              @avatar_file = "./public/uploads/images/companies/#{@current_user.company.id}.#{@format}"
                
              FileUtils.cp(@avatar.tempfile, @avatar_file)
              if File.exist?(@avatar.tempfile)
                redirect_to '/user_company_index'
              else
                @avatar_errors.push("Não foi possível fazer o upload da sua imagem. Tente novamente mais tarde.")
                redirect_to '/user_company', notice: @avatar_errors
              end
            else
              @avatar_errors.push("O formato da imagem é inválido. A imagem deve estar no formato JPEG ('*.jpg') ou PNG ('*.png').")
              redirect_to'/user_company', notice: @avatar_errors
            end
          else
            @avatar_errors.push("O tamanho da imagem deve ser de exatamente 198 por 71 pixels (198x71px).")
            redirect_to '/user_company', notice: @avatar_errors
          end
        else
          @avatar_errors.push("Selecione uma imagem do seu computador.")
          redirect_to '/user_company', notice: @avatar_errors
        end
      }
    end
  end

end

app/views/companies/_edit_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "erro") %> encontrado(s):</h2>
      <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
         <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <fieldset>
      <label>Dados da empresa</label>
      <section><label for="text_field">CNPJ</label>
        <div><%= text_field_tag 'company[legal_identifier]',@company.legal_identifier, type: "text", class: "g4"%></div>
      </section>   
      <section><label for="text_field">Razão social</label>
        <div><%= text_field_tag 'company[legal_name]',@company.legal_name, type: "text"%></div>
      </section>   
      <section><label for="text_field">Nome fantasia</label>
        <div><%= text_field_tag 'company[trade_name]',@company.trade_name, type: "text"%></div>
      </section>
      <section><label for="email_field">Email para contato</label>
        <div><%= email_field_tag 'company[contact_email]',@company.contact_email, type: "email",class: "g5"%></div>
      </section>
      <section><label for="">Telefone de contato</label>
        <div><input type="text" id="regex_number" name="company[contact_phone]" data-regex="^[0-9 ]+$" class="g5" value="<%=@company.contact_phone%>" ></div>
      </section>
      <section><label for="email_field">Nome para contato</label>
        <div><%= text_field_tag 'company[contact_name]',@company.contact_name,class: "g5", type: "text"%></div>
      </section>
      <section><label for="">Endereço</label>
        <div>
          <%= text_field_tag 'company[address]',@company.address, type: "text",class: "g5"%>
          <%= text_field_tag 'company[address_neighbourhood]',@company.address_neighbourhood, type: "text",class: "g3"%>
          <span style="padding: 0; margin: 0; margin-right: 16px" class="g5">Logradouro (rua/avenida, numero, complemento)</span>
          <span style="padding: 0; margin: 0; margin-right: 16px" class="g3">Bairro</span> 
          <br/><br/>
          <% if @company.city == nil %>
            <%
              state_options = ""
              State.all.each do |state|
                state_options += "<option value=\"#{state.id}\">#{state.name}</option>"
              end 
            %>
            <br/><br/>
            Estado:<%= select_tag  'state_id', state_options.html_safe, :prompt => "Estado", id: "cod_estados", style: "width: 97%"  ,required: "required"%>    
            Cidade:<%= select_tag  'company[city_id]', "", :prompt => "Cidade", id: "cod_cidades", style: "width: 97%"  ,required: "required"%>
          <% else %>
            <div>
            <%
              state_options = ""
              state_options_selected = ""

              State.all.each do |state|
              if @company.city == nil
                state_options_selected = ""
              elsif state.id == @company.city.state.id
                state_options_selected = "selected"
              else
                state_options_selected = ""
              end
              state_options += "<option #{state_options_selected} value=\"#{state.id}\">#{state.name}</option>"
              end 
            %>
            <%
              city_options = ""
              city_options_selected = ""

              cities = City.where(:state_id => @company.city.state.id)
              cities.each do |city|
                if @company.city == nil
                 city_options_selected = ""
                elsif city.id == @company.city.id
                  city_options_selected = "selected"
                else
                  city_options_selected = ""
                end
                  city_options += "<option #{city_options_selected} value=\"#{city.id}\">#{city.name}</option>"
              end 
            %>
            <br/><br/>
            Estado:<%= select_tag  'state_id', state_options.html_safe, prompt: "Estado", id: 'cod_estados', class: 'rounded_form_field',  style: "width: 97%" ,required: "required"%>
          Cidade:<%= select_tag  'company[city_id]', city_options.html_safe, prompt: "Cidade", id: 'cod_cidades', class: 'rounded_form_field',  style: "width: 97%" ,required: "required" %>
        </div>
          <% end %>
            
        </div>
      </section>
      <section>
        <div><%= f.submit "Salvar"%></div>
      </section>
    </fieldset>
  </div>
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "erro") %> encontrado(s):</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="actions">
 <fieldset>
        <label>Dados da Empresa</label>

        <section><label for="text_field">CNPJ</label>
          <div><%= text_field_tag 'company[legal_identifier]',nil, type: "text", class: "g4",required: "required"%></div>
        </section>   
        <section><label for="text_field">Razão social</label>
          <div><%= text_field_tag 'company[legal_name]',nil, type: "text",required: "required"%></div>
        </section>   
        <section><label for="text_field">Nome fantasia</label>
          <div><%= text_field_tag 'company[trade_name]',nil, type: "text",required: "required"%></div>
        </section>
        <section><label for="email_field">Email para contato</label>
          <div><%= email_field_tag 'company[contact_email]',nil, type: "email",class: "g5"%></div>
        </section>
        <section><label for="">Telefone de contato</label>
          <div><input type="text" id="regex_number" name="company[contact_phone]" data-regex="^[0-9 ]+$" class="g5" ></div>
        </section>
         <section><label for="email_field">Nome para contato</label>
          <div><%= text_field_tag 'company[contact_name]',nil,class: "g5", type: "text"%></div>
        </section>
        <section><label for="">Endereço</label>
          <div>
           <%= text_field_tag 'company[address]',nil, type: "text",class: "g5",required: "required"%>
                <%= text_field_tag 'company[address_neighbourhood]',nil, type: "text",class: "g3",required: "required"%>
        <%
          state_options = ""
          State.all.each do |state|
            state_options += "<option value=\"#{state.id}\">#{state.name}</option>"
          end 
        %>
        <%= select_tag  'state_id', state_options.html_safe, :prompt => "Estado", id: "cod_estados", style: "width: 97%" ,required: "required"%>    
        <%= select_tag  'company[city_id]', "", :prompt => "Cidade", id: "cod_cidades", style: "width: 97%" ,required: "required" %>
            
            <span style="padding: 0; margin: 0; margin-right: 16px" class="g5">Logradouro (rua/avenida, numero, complemento)</span>
            <span style="padding: 0; margin: 0; margin-right: 16px" class="g3">Bairro</span>


          </div>
        </section>
      <section>
        <div>
           <%= f.submit "Cadastrar", :class => "submit"%>
        </div>
      </section>
      </fieldset>

    
  </div>
<% end %>

app/views/companies/_form_user_company.html.erb
<fieldset >
				<label class="noprint-noshadow">Dados da empresa</label>
				<section><label for="text_field">CNPJ</label>
					<div>
						<p><%= @company.legal_identifier %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="">Razão social</label>
					<div>
						<p><%= @company.legal_name %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="">Nome fantasia</label>
					<div>
						<p><%= @company.trade_name %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Email para contato</label>
					<div>
						<p><%= @company.contact_email %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Telefone de contato</label>
					<div>
						<p><%= @company.contact_phone %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Nome para contato</label>
					<div>
						<p><%= @company.contact_name %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Endereço</label>
					<div>
						<p><p><%= @company.address%><%=" - "%><%= @company.address_neighbourhood%></p>
					</div>
				</section>
				<% if  @company.city == nil
					varcity = '-'
					varstate = '-'
				   else
				   	varcity = @company.city.name
				   	varstate = @company.city.state.name
				   end %>
				<section><label class="noprint-noshadow"for="text_tooltip">Cidade</label>
					<div>
						<p><%= varcity %></p>
					</div>
				</section>
				<section><label class="noprint-noshadow" for="text_tooltip">Estado</label>
					<div>
						<p><%= varstate %></p>
					</div>
				</section>
			</fieldset>

app/views/companies/edit.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12">
		<h1>Editar empresa</h1>
		<p>Editar informações da empresa</p>
		<form id="form" action="" method="post" autocomplete="off">
			<%= render 'edit_form' %>
		</form>
		<%=form_tag({ controller: "companies", action: "set_avatar"}, { :id => "set_avatar_form", :multipart => true }) do %>
		<h3>Definir logomarca para empresa</h3>

			<%= hidden_field_tag "id", params[:id]%>
				<%= field_set_tag do %>
			      <%= file_field 'avatar', nil, :multipart => true  %>
			    <%end%>
			    <div style="clear: both; padding-top: 20px"></div>

			    <%= link_to "Voltar", "/companies",class: 'button small', style: 'margin-right: 10px;' %> |
			    <a id="finish_btn" href="#" class='button small' onclick="$('#set_avatar_form').submit();"><span class="triangle"></span> Concluir</a>
			<%end%>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/companies/index.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section id="content" class="content">
  <h1>Empresas</h1>
    <p>Dados das empresas</p>
  <p><%= link_to 'Nova empresa', new_company_path, class: 'btn' %></p>

  <div class="g12">
    <% if @companies.empty? %>
    <br />
    <h4>Ainda não possui nenhum empresa cadastrada, clique em Nova Empresa para cadastrar</h4>
    <% else %>
  
    <table class="datatable">
      <thead>
        <tr>
          <th>CNPJ<div class="icon_order"></div></th>
          <th>Nome fantasia<div class="icon_order"></div></th>
          <th>Estado<div class="icon_order"></div></th>
          <th>Cidade<div class="icon_order"></div></th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
        <tr class="gradeA">
          <%if  company.city == nil
              varcity = '-'
              varstate = '-'
            else
              varcity = company.city.name 
              varstate = company.city.state.name             
            end 
          %>

          <td><%= company.legal_identifier %></td>
          <td><%= company.trade_name %></td>
          <td><%= varstate%></td>
          <td><%= varcity %></td>
          
          <td><%= link_to 'Visualizar', company, class: 'btn small' %><%= link_to 'Editar', edit_company_path(company), class: 'btn small' %><%= link_to 'Deletar', company, method: :delete, data: { confirm: 'Você tem certeza?' }, class: 'btn small' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</section>
<%= render 'welcome/partials/footer' %>

app/views/companies/new.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12"> 
		<h1>Cadastrar nova empresa</h1>
		<p>Preencha os dados e cadastre uma nova empresa</p>
		<form id="form" action="" method="post" autocomplete="off">
			<%= render 'form' %>
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/companies/show.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
	


<section class="content">
	
	<div class="g12">
		<h1>Empresa</h1>
		<p>Informações da empresa</p>
		 <%=
       @avatar_file_jpg = "/uploads/images/companies/#{@company.id}.jpg"
       @avatar_file_png = "/uploads/images/companies/#{@company.id}.png"
       if File.exist?("./public#{@avatar_file_jpg}")
                   "<img src=\"#{@avatar_file_jpg}\" alt=\"\" />".html_safe
       elsif File.exist?("./public#{@avatar_file_png}" )
               "<img src=\"#{@avatar_file_png}\" alt=\"\" />".html_safe
       end
    %>
		<p id="notice"><%= notice %></p>
		
		<form id="form">

			<fieldset>
				<div><label>Dados da empresa</label><p><%= link_to 'Editar', edit_company_path(@company), class: 'button small' %>
	</p></div>
	<section><label for="text_field">ID da empresa</label>
					<div>
						<p><%= @company.id %></p>
					</div>
				</section>
			<section><label for="text_field">CNPJ</label>
					<div>
						<p><%= @company.legal_identifier %></p>
					</div>
				</section>
				<section><label for="">Razão social</label>
					<div>
						<p><%= @company.legal_name %></p>
					</div>
				</section>
				<section><label for="">Nome fantasia</label>
					<div>
						<p><%= @company.trade_name %></p>
					</div>
				</section>
				<section><label for="text_tooltip">Email para contato</label>
					<div>
						<p><%= @company.contact_email %></p>
					</div>
				</section>
				<section><label for="text_tooltip">Telefone de contato</label>
					<div>
						<p><%= @company.contact_phone %></p>
					</div>
				</section>
				<section><label for="text_tooltip">Nome para contato</label>
					<div>
						<p><%= @company.contact_name %></p>
					</div>
				</section>
				<section><label for="text_tooltip">Endereço</label>
					<div>
						<p><p><%= @company.address%><%=" - "%><%= @company.address_neighbourhood%></p></p>
					</div>
				</section>
				<% if  @company.city == nil
					varcity = '-'
					varstate = '-'
				   else
				   	varcity = @company.city.name
				   	varstate = @company.city.state.name
				   end %>
				<section><label for="text_tooltip">Cidade</label>
					<div>
						<p><%= varcity %></p>
					</div>
				</section>
				<section><label for="text_tooltip">Estado</label>
					<div>
						<p><%= varstate %></p>
					</div>
				</section>
			</fieldset>
		</form>
		<%= link_to 'Voltar', companies_path, class: 'button small' %>
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/companies/user_company.html.erb
<body>
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>

<section class="content">
	<div class="g12">
		<h1>Empresa</h1>
		<p>Editar a logo da sua empresa.</p>
		<p id="notice"><%= notice %></p>
		<%=form_tag({ controller: "companies", action: "user_set_avatar"}, { :id => "set_avatar_form", :multipart => true }) do %>
		<h3>Definir logomarca para empresa</h3>

			<%= hidden_field_tag "id", params[:id]%>
				<%= field_set_tag do %>
			      <%= file_field 'avatar', nil, :multipart => true  %>
			    <%end%>
			    <div style="clear: both; padding-top: 20px"></div>

			<%= link_to 'Voltar', "/user_company_index", class: 'button small' %>
			    |
			    <a id="finish_btn" href="#" class='button small' onclick="$('#set_avatar_form').submit();"><span class="triangle"></span> Concluir</a>
			<%end%>
		<form id="form">
			<%= render 'form_user_company' %>
		</form>
		
	</div>
</section>

<%= render 'welcome/partials/footer' %>

app/views/companies/user_company_index.html.erb
<%= stylesheet_link_tag 'print', :media => 'print' %>

<body class="noprint-fontcolor">
<%= render 'welcome/partials/admin_header' %>
<%= render 'welcome/partials/admin_nav' %>
<script type="text/javascript">
  function DoPrinting() {
       if (!window.print){
               alert("Use o Netscape  ou Internet Explorer \n nas versões 4.0 ou superior!");
               return;
       }
       window.print();
  }
</script>
<section class="content noprint-relatorio-content">
	<div class="g12 ">
		<h1 class="noprint-noshadow">Empresa</h1>
    <p>Dados da empresa<br/><a href="#" onclick="DoPrinting()" class="noprint">Imprimir</a> </p>
		<%=
       @avatar_file_jpg = "/uploads/images/companies/#{@company.id}.jpg"
       @avatar_file_png = "/uploads/images/companies/#{@company.id}.png"
       if File.exist?("./public#{@avatar_file_jpg}")
          "<img src=\"#{@avatar_file_jpg}\" alt=\"\" />".html_safe
       elsif File.exist?("./public#{@avatar_file_png}" )
          "<img src=\"#{@avatar_file_png}\" alt=\"\" />".html_safe
       end
    %>
    <p>
   <%= link_to ' Definir logomarca', "/user_company", class: 'button small noprint' %></p>
		<p class="noprint" id="notice"><%= notice %></p>
		<form id="form">
			<%= render 'form_user_company' %>
		</form>
	</div>
</section>

<%= render 'welcome/partials/footer' %>